//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupClaim) DeepCopyInto(out *BackupClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupClaim.
func (in *BackupClaim) DeepCopy() *BackupClaim {
	if in == nil {
		return nil
	}
	out := new(BackupClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupClaimDestinationSpec) DeepCopyInto(out *BackupClaimDestinationSpec) {
	*out = *in
	in.Pod.DeepCopyInto(&out.Pod)
	out.ExistingPod = in.ExistingPod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupClaimDestinationSpec.
func (in *BackupClaimDestinationSpec) DeepCopy() *BackupClaimDestinationSpec {
	if in == nil {
		return nil
	}
	out := new(BackupClaimDestinationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupClaimExistingPodDestinationSpec) DeepCopyInto(out *BackupClaimExistingPodDestinationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupClaimExistingPodDestinationSpec.
func (in *BackupClaimExistingPodDestinationSpec) DeepCopy() *BackupClaimExistingPodDestinationSpec {
	if in == nil {
		return nil
	}
	out := new(BackupClaimExistingPodDestinationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupClaimList) DeepCopyInto(out *BackupClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupClaimList.
func (in *BackupClaimList) DeepCopy() *BackupClaimList {
	if in == nil {
		return nil
	}
	out := new(BackupClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupClaimNewPodDestinationSpec) DeepCopyInto(out *BackupClaimNewPodDestinationSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupClaimNewPodDestinationSpec.
func (in *BackupClaimNewPodDestinationSpec) DeepCopy() *BackupClaimNewPodDestinationSpec {
	if in == nil {
		return nil
	}
	out := new(BackupClaimNewPodDestinationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupClaimS3SourceSpec) DeepCopyInto(out *BackupClaimS3SourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupClaimS3SourceSpec.
func (in *BackupClaimS3SourceSpec) DeepCopy() *BackupClaimS3SourceSpec {
	if in == nil {
		return nil
	}
	out := new(BackupClaimS3SourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupClaimSourceSpec) DeepCopyInto(out *BackupClaimSourceSpec) {
	*out = *in
	out.S3 = in.S3
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupClaimSourceSpec.
func (in *BackupClaimSourceSpec) DeepCopy() *BackupClaimSourceSpec {
	if in == nil {
		return nil
	}
	out := new(BackupClaimSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupClaimSpec) DeepCopyInto(out *BackupClaimSpec) {
	*out = *in
	out.Source = in.Source
	in.Destination.DeepCopyInto(&out.Destination)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupClaimSpec.
func (in *BackupClaimSpec) DeepCopy() *BackupClaimSpec {
	if in == nil {
		return nil
	}
	out := new(BackupClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupClaimStatus) DeepCopyInto(out *BackupClaimStatus) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ResolvedAt != nil {
		in, out := &in.ResolvedAt, &out.ResolvedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupClaimStatus.
func (in *BackupClaimStatus) DeepCopy() *BackupClaimStatus {
	if in == nil {
		return nil
	}
	out := new(BackupClaimStatus)
	in.DeepCopyInto(out)
	return out
}
